create table "public"."month" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."month" enable row level security;

CREATE UNIQUE INDEX month_pkey ON public.month USING btree (id);

alter table "public"."month" add constraint "month_pkey" PRIMARY KEY using index "month_pkey";

grant delete on table "public"."month" to "anon";

grant insert on table "public"."month" to "anon";

grant references on table "public"."month" to "anon";

grant select on table "public"."month" to "anon";

grant trigger on table "public"."month" to "anon";

grant truncate on table "public"."month" to "anon";

grant update on table "public"."month" to "anon";

grant delete on table "public"."month" to "authenticated";

grant insert on table "public"."month" to "authenticated";

grant references on table "public"."month" to "authenticated";

grant select on table "public"."month" to "authenticated";

grant trigger on table "public"."month" to "authenticated";

grant truncate on table "public"."month" to "authenticated";

grant update on table "public"."month" to "authenticated";

grant delete on table "public"."month" to "service_role";

grant insert on table "public"."month" to "service_role";

grant references on table "public"."month" to "service_role";

grant select on table "public"."month" to "service_role";

grant trigger on table "public"."month" to "service_role";

grant truncate on table "public"."month" to "service_role";

grant update on table "public"."month" to "service_role";


