create table "public"."register" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "month" bigint,
    "minutes" numeric,
    "user" uuid default auth.uid()
);


alter table "public"."register" enable row level security;

CREATE UNIQUE INDEX register_pkey ON public.register USING btree (id);

alter table "public"."register" add constraint "register_pkey" PRIMARY KEY using index "register_pkey";

alter table "public"."register" add constraint "register_month_fkey" FOREIGN KEY (month) REFERENCES month(id) not valid;

alter table "public"."register" validate constraint "register_month_fkey";

alter table "public"."register" add constraint "register_user_fkey" FOREIGN KEY ("user") REFERENCES auth.users(id) not valid;

alter table "public"."register" validate constraint "register_user_fkey";

grant delete on table "public"."register" to "anon";

grant insert on table "public"."register" to "anon";

grant references on table "public"."register" to "anon";

grant select on table "public"."register" to "anon";

grant trigger on table "public"."register" to "anon";

grant truncate on table "public"."register" to "anon";

grant update on table "public"."register" to "anon";

grant delete on table "public"."register" to "authenticated";

grant insert on table "public"."register" to "authenticated";

grant references on table "public"."register" to "authenticated";

grant select on table "public"."register" to "authenticated";

grant trigger on table "public"."register" to "authenticated";

grant truncate on table "public"."register" to "authenticated";

grant update on table "public"."register" to "authenticated";

grant delete on table "public"."register" to "service_role";

grant insert on table "public"."register" to "service_role";

grant references on table "public"."register" to "service_role";

grant select on table "public"."register" to "service_role";

grant trigger on table "public"."register" to "service_role";

grant truncate on table "public"."register" to "service_role";

grant update on table "public"."register" to "service_role";

create policy "only read"
on "public"."month"
as permissive
for select
to authenticated
using (true);


create policy "register"
on "public"."register"
as permissive
for all
to authenticated
using (("user" = auth.uid()))
with check (("user" = auth.uid()));



